version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      react-dependencies:
        patterns:
          - "react*"
          - "@testing-library/react"
        update-types:
          - "minor"
          - "patch"
      major-react-dependencies:
        patterns:
          - "react*"
          - "@testing-library/react"
        update-types:
          - "major"
      testing-dependencies:
        patterns:
          - "@eslint/*"
          - "@playwright/test"
          - "@testing-library/*"
          - "@vitejs/plugin-react"
          - "eslint*"
          - "playwright"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      major-testing-dependencies:
        patterns:
          - "@eslint/*"
          - "@playwright/test"
          - "@testing-library/*"
          - "@vitejs/plugin-react"
          - "eslint*"
          - "playwright"
          - "prettier"
        update-types:
          - "major"
      contentful-dependencies:
        patterns:
          - "@contentful/*"
        update-types:
          - "minor"
          - "patch"
      # everything else
      js-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      # anything not caught be these groups above will be a major non-testing, non-react js update and should be raised in its own PR
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[dependabot:actions] "
    groups:
      regular-updates: # Group everything except major version updates and security vulnerabilities
        update-types:
          - "minor"
          - "patch"
