name: Deploy unstable app
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    environment:
      name: unstable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install npm packages
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_REACT_APP_CONTENTFUL_ENV: ${{ vars.CONTENTFUL_ENV }}
          VITE_REACT_APP_CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}

      - name: Deploy
        run: npm run upload-ci -- --comment "Deployed by GitHub ${GITHUB_SHA}"
        env:
          CONTENTFUL_ORG_ID: ${{ secrets.CONTENTFUL_ORG_ID }}
          CONTENTFUL_APP_DEF_ID: ${{ secrets.UNSTABLE_APP_DEFINITION_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
